#pragma once
#include <windows.h>

#define NPPMSG (WM_USER + 1000)
#define NPPM_GETCURRENTSCINTILLA (NPPMSG + 4)
#define NPPM_MODELESSDIALOG (NPPMSG + 12)
#define MODELESSDIALOGADD 0
#define MODELESSDIALOGREMOVE 1
#define NPPM_CREATESCINTILLAHANDLE (NPPMSG + 20)
#define NPPM_GETMENUHANDLE   (NPPMSG + 25)
#define NPPMAINMENU          1
#define NPPM_ALLOCATECMDID   (NPPMSG + 81)
#define NPPM_DOOPEN          (NPPMSG + 77)

#define NPPN_FIRST           1000
#define NPPN_SHUTDOWN        (NPPN_FIRST + 9)

#define NPPM_DMMREGASDCKDLG (NPPMSG + 33)
#define NPPM_DMMSHOW (NPPMSG + 30)
#define NPPM_DMMHIDE (NPPMSG + 31)
#define NPPM_DMMUPDATEDISPINFO (NPPMSG + 32)
